monitoring:
  mgmt_ip: 192.168.1.10
  ip: 192.168.1.10
routing:
  monitoring:
      - 192.168.1.10
  ip: 192.168.1.10
server:
  monitoring:
      - 192.168.1.10
  routing: 
      - 192.168.1.10
  seed_ip: 192.168.1.10
  public_ip: 192.168.1.10
  private_ip: 192.168.1.10
  mgmt_ip: "NULL"
policy:
  elasticity: false
  selective-rep: false
  tiering: false
capacities: # in GB
  memory-cap: 1
  ebs-cap: 80
threads:
  memory: 1
  ebs: 50
  routing: 4
  benchmark: 1
replication:
  memory: 0
  ebs: 1
  minimum: 0
  local: 1
