user:
  monitoring:
      - 192.168.1.10
  routing: 
      - 192.168.1.10
  ip: 192.168.1.13
policy:
  elasticity: false
  selective-rep: false
  tiering: false
benchmark:
  - 192.168.1.13
middleware:
  type: 1
capacities: # in GB
  memory-cap: 1
  ebs-cap: 80
threads:
  memory: 1
  ebs: 50
  routing: 4
  benchmark: 40
replication:
  memory: 0
  ebs: 1
  minimum: 0
  local: 1
