server:
  monitoring:
      - 192.168.1.10
  routing: 
      - 192.168.1.10
  seed_ip: 192.168.1.10
  public_ip: 192.168.1.11
  private_ip: 192.168.1.11
  mgmt_ip: "NULL"
policy:
  elasticity: false
  selective-rep: false
  tiering: false
ebs: /data
capacities: # in GB
  memory-cap: 1
  ebs-cap: 80
threads:
  memory: 10
  ebs: 10
  routing: 4
  benchmark: 1
replication:
  memory: 1
  ebs: 1
  minimum: 1
  local: 1
