version: "3"
services:
  mem:
    image: anna-kvs
    command: bash start-anna.sh mem
    volumes:
      - ./conf/anna-config-mem.yml:/hydro/anna/conf/anna-config.yml
    networks:
      anna_network:
        ipv4_address: 192.168.1.10
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
  ebs:
    image: anna-kvs
    command: bash start-anna.sh ebs
    volumes:
      - ./conf/anna-config-ebs.yml:/hydro/anna/conf/anna-config.yml
      - /mnt/pmem0/data:/data
    networks:
      anna_network:
        ipv4_address: 192.168.1.11
    depends_on:
      - mem
  bench:
    image: anna-kvs
    command: bash start-anna.sh b
    volumes:
      - ./conf/anna-config-bench.yml:/hydro/anna/conf/anna-config.yml
    networks:
      anna_network:
        ipv4_address: 192.168.1.12
    depends_on:
      - mem
networks:
  anna_network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
